# Generated by Django 4.1.7 on 2023-02-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(help_text='Выберите автора книги', to='bibliotek.author', verbose_name='Автор'),
        ),
    ]
